version: "3.8"

services:
  server:
    build:
      context: .
    ports:
      - 4000:4000
    volumes:
      - ./:/app
    depends_on:
      - rabbitmq
    healthcheck:
      test:
        ["curl", "-f", "http://localhost:4000/.well-known/apollo/server-health"]
    command:
      ["./.wait-for-it.sh", "rabbitmq:15672", "--", "npm", "run", "server"]
  reddit:
    build:
      context: .
    volumes:
      - ./:/app
    depends_on:
      - rabbitmq
    command:
      ["./.wait-for-it.sh", "rabbitmq:15672", "--", "npm", "run", "reddit"]
  rabbitmq:
    image: rabbitmq:3.9-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
