version: "3.8"

services:
  server:
    build:
      context: .
    ports:
      - 4000:4000
    volumes:
      - ./:/app
    command: ["./.wait-for-it.sh", "rabbitmq:15672", "--", "npm", "run", "dev"]
  # reddit:
  #   build:
  #     context: .
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - rabbitmq
  #   command:
  #     ["./.wait-for-it.sh", "rabbitmq:15672", "--", "npm", "run", "reddit"]
  rabbitmq:
    image: rabbitmq:3.9-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
