version: "3.8"

services:
  server:
    build:
      context: .
    ports:
      - 4000:4000
    volumes:
      - ./:/app
    command: ["./.wait-for-it.sh", "rabbitmq:15672", "--", "npm", "run", "dev"]
  # Requires CentralCodgma and SEELE to be in a shared folder
  metacritic_worker:
    build:
      context: ../SEELE/
    volumes:
      # Point to the location of SEELE workspace
      - ../SEELE/:/app
    command: ["npx", "nodemon", "workers/meta_critic.py"]
    deploy:
      replicas: 3
    environment:
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
  rabbitmq:
    image: "rabbitmq:3.9-management"
    ports:
      - 5672:5672
      - 15672:15672
  selenium_grid:
    image: "selenium/standalone-chrome:latest"
    ports:
      - 4444:4444
    shm_size: "2g"
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  # Only needed to debug redis and thus can be commented out
  redis-insight:
    image: "redislabs/redisinsight:latest"
    volumes:
      - redis-insight-data:/db
    ports:
      - 8001:8001

volumes:
  redis-insight-data:
    external: false
